// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"task_manager/domain"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// AddTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) AddTask(task domain.Task) (domain.Task, error) {
	ret := _mock.Called(task)

	if len(ret) == 0 {
		panic("no return value specified for AddTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.Task) (domain.Task, error)); ok {
		return returnFunc(task)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.Task) domain.Task); ok {
		r0 = returnFunc(task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.Task) error); ok {
		r1 = returnFunc(task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_AddTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTask'
type MockTaskRepository_AddTask_Call struct {
	*mock.Call
}

// AddTask is a helper method to define mock.On call
//   - task domain.Task
func (_e *MockTaskRepository_Expecter) AddTask(task interface{}) *MockTaskRepository_AddTask_Call {
	return &MockTaskRepository_AddTask_Call{Call: _e.mock.On("AddTask", task)}
}

func (_c *MockTaskRepository_AddTask_Call) Run(run func(task domain.Task)) *MockTaskRepository_AddTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.Task
		if args[0] != nil {
			arg0 = args[0].(domain.Task)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_AddTask_Call) Return(task1 domain.Task, err error) *MockTaskRepository_AddTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskRepository_AddTask_Call) RunAndReturn(run func(task domain.Task) (domain.Task, error)) *MockTaskRepository_AddTask_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) DeleteTask(id primitive.ObjectID) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(primitive.ObjectID) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_DeleteTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTask'
type MockTaskRepository_DeleteTask_Call struct {
	*mock.Call
}

// DeleteTask is a helper method to define mock.On call
//   - id primitive.ObjectID
func (_e *MockTaskRepository_Expecter) DeleteTask(id interface{}) *MockTaskRepository_DeleteTask_Call {
	return &MockTaskRepository_DeleteTask_Call{Call: _e.mock.On("DeleteTask", id)}
}

func (_c *MockTaskRepository_DeleteTask_Call) Run(run func(id primitive.ObjectID)) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 primitive.ObjectID
		if args[0] != nil {
			arg0 = args[0].(primitive.ObjectID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) Return(err error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_DeleteTask_Call) RunAndReturn(run func(id primitive.ObjectID) error) *MockTaskRepository_DeleteTask_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllTasks provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetAllTasks() ([]domain.Task, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllTasks")
	}

	var r0 []domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]domain.Task, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []domain.Task); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllTasks'
type MockTaskRepository_GetAllTasks_Call struct {
	*mock.Call
}

// GetAllTasks is a helper method to define mock.On call
func (_e *MockTaskRepository_Expecter) GetAllTasks() *MockTaskRepository_GetAllTasks_Call {
	return &MockTaskRepository_GetAllTasks_Call{Call: _e.mock.On("GetAllTasks")}
}

func (_c *MockTaskRepository_GetAllTasks_Call) Run(run func()) *MockTaskRepository_GetAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockTaskRepository_GetAllTasks_Call) Return(tasks []domain.Task, err error) *MockTaskRepository_GetAllTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetAllTasks_Call) RunAndReturn(run func() ([]domain.Task, error)) *MockTaskRepository_GetAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskDetails provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetTaskDetails(id primitive.ObjectID) (domain.Task, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskDetails")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(primitive.ObjectID) (domain.Task, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(primitive.ObjectID) domain.Task); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(primitive.ObjectID) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetTaskDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskDetails'
type MockTaskRepository_GetTaskDetails_Call struct {
	*mock.Call
}

// GetTaskDetails is a helper method to define mock.On call
//   - id primitive.ObjectID
func (_e *MockTaskRepository_Expecter) GetTaskDetails(id interface{}) *MockTaskRepository_GetTaskDetails_Call {
	return &MockTaskRepository_GetTaskDetails_Call{Call: _e.mock.On("GetTaskDetails", id)}
}

func (_c *MockTaskRepository_GetTaskDetails_Call) Run(run func(id primitive.ObjectID)) *MockTaskRepository_GetTaskDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 primitive.ObjectID
		if args[0] != nil {
			arg0 = args[0].(primitive.ObjectID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetTaskDetails_Call) Return(task domain.Task, err error) *MockTaskRepository_GetTaskDetails_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetTaskDetails_Call) RunAndReturn(run func(id primitive.ObjectID) (domain.Task, error)) *MockTaskRepository_GetTaskDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTask provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) UpdateTask(id primitive.ObjectID, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(id, task)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(primitive.ObjectID, domain.Task) (domain.Task, error)); ok {
		return returnFunc(id, task)
	}
	if returnFunc, ok := ret.Get(0).(func(primitive.ObjectID, domain.Task) domain.Task); ok {
		r0 = returnFunc(id, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(primitive.ObjectID, domain.Task) error); ok {
		r1 = returnFunc(id, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_UpdateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTask'
type MockTaskRepository_UpdateTask_Call struct {
	*mock.Call
}

// UpdateTask is a helper method to define mock.On call
//   - id primitive.ObjectID
//   - task domain.Task
func (_e *MockTaskRepository_Expecter) UpdateTask(id interface{}, task interface{}) *MockTaskRepository_UpdateTask_Call {
	return &MockTaskRepository_UpdateTask_Call{Call: _e.mock.On("UpdateTask", id, task)}
}

func (_c *MockTaskRepository_UpdateTask_Call) Run(run func(id primitive.ObjectID, task domain.Task)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 primitive.ObjectID
		if args[0] != nil {
			arg0 = args[0].(primitive.ObjectID)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) Return(task1 domain.Task, err error) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskRepository_UpdateTask_Call) RunAndReturn(run func(id primitive.ObjectID, task domain.Task) (domain.Task, error)) *MockTaskRepository_UpdateTask_Call {
	_c.Call.Return(run)
	return _c
}
