// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"task_manager/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) Login(username string, password string) (string, error) {
	ret := _mock.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return returnFunc(username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = returnFunc(username, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockUserUsecase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockUserUsecase_Expecter) Login(username interface{}, password interface{}) *MockUserUsecase_Login_Call {
	return &MockUserUsecase_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockUserUsecase_Login_Call) Run(run func(username string, password string)) *MockUserUsecase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUsecase_Login_Call) Return(s string, err error) *MockUserUsecase_Login_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserUsecase_Login_Call) RunAndReturn(run func(username string, password string) (string, error)) *MockUserUsecase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) Register(user domain.User) (domain.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.User) (domain.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.User) domain.User); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserUsecase_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - user domain.User
func (_e *MockUserUsecase_Expecter) Register(user interface{}) *MockUserUsecase_Register_Call {
	return &MockUserUsecase_Register_Call{Call: _e.mock.On("Register", user)}
}

func (_c *MockUserUsecase_Register_Call) Run(run func(user domain.User)) *MockUserUsecase_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.User
		if args[0] != nil {
			arg0 = args[0].(domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserUsecase_Register_Call) Return(user1 domain.User, err error) *MockUserUsecase_Register_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserUsecase_Register_Call) RunAndReturn(run func(user domain.User) (domain.User, error)) *MockUserUsecase_Register_Call {
	_c.Call.Return(run)
	return _c
}
