// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"task_manager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// GetByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetByUsername(username string) (domain.User, error) {
	ret := _mock.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.User, error)); ok {
		return returnFunc(username)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.User); ok {
		r0 = returnFunc(username)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepository_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockUserRepository_Expecter) GetByUsername(username interface{}) *MockUserRepository_GetByUsername_Call {
	return &MockUserRepository_GetByUsername_Call{Call: _e.mock.On("GetByUsername", username)}
}

func (_c *MockUserRepository_GetByUsername_Call) Run(run func(username string)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) Return(user domain.User, err error) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_GetByUsername_Call) RunAndReturn(run func(username string) (domain.User, error)) *MockUserRepository_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Register(user domain.User) (domain.User, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(domain.User) (domain.User, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(domain.User) domain.User); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(domain.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserRepository_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - user domain.User
func (_e *MockUserRepository_Expecter) Register(user interface{}) *MockUserRepository_Register_Call {
	return &MockUserRepository_Register_Call{Call: _e.mock.On("Register", user)}
}

func (_c *MockUserRepository_Register_Call) Run(run func(user domain.User)) *MockUserRepository_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 domain.User
		if args[0] != nil {
			arg0 = args[0].(domain.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_Register_Call) Return(user1 domain.User, err error) *MockUserRepository_Register_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_Register_Call) RunAndReturn(run func(user domain.User) (domain.User, error)) *MockUserRepository_Register_Call {
	_c.Call.Return(run)
	return _c
}
